// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AcquisitionSpecApplyConfiguration represents a declarative configuration of the AcquisitionSpec type for use
// with apply.
//
// AcquisitionSpec defines how to acquire/receive the IPv6 prefix
type AcquisitionSpecApplyConfiguration struct {
	// DHCPv6PD configures DHCPv6 Prefix Delegation to receive prefix from upstream router
	DHCPv6PD *DHCPv6PDSpecApplyConfiguration `json:"dhcpv6pd,omitempty"`
	// RouterAdvertisement configures Router Advertisement monitoring as fallback
	RouterAdvertisement *RouterAdvertisementSpecApplyConfiguration `json:"routerAdvertisement,omitempty"`
	// PrefixFilter constrains which acquired prefixes are accepted, independent of
	// the acquisition source.
	PrefixFilter *PrefixFilterSpecApplyConfiguration `json:"prefixFilter,omitempty"`
}

// AcquisitionSpecApplyConfiguration constructs a declarative configuration of the AcquisitionSpec type for use with
// apply.
func AcquisitionSpec() *AcquisitionSpecApplyConfiguration {
	return &AcquisitionSpecApplyConfiguration{}
}

// WithDHCPv6PD sets the DHCPv6PD field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPv6PD field is set to the value of the last call.
func (b *AcquisitionSpecApplyConfiguration) WithDHCPv6PD(value *DHCPv6PDSpecApplyConfiguration) *AcquisitionSpecApplyConfiguration {
	b.DHCPv6PD = value
	return b
}

// WithRouterAdvertisement sets the RouterAdvertisement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouterAdvertisement field is set to the value of the last call.
func (b *AcquisitionSpecApplyConfiguration) WithRouterAdvertisement(value *RouterAdvertisementSpecApplyConfiguration) *AcquisitionSpecApplyConfiguration {
	b.RouterAdvertisement = value
	return b
}

// WithPrefixFilter sets the PrefixFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixFilter field is set to the value of the last call.
func (b *AcquisitionSpecApplyConfiguration) WithPrefixFilter(value *PrefixFilterSpecApplyConfiguration) *AcquisitionSpecApplyConfiguration {
	b.PrefixFilter = value
	return b
}
