// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AddressRangeSpecApplyConfiguration represents a declarative configuration of the AddressRangeSpec type for use
// with apply.
//
// AddressRangeSpec defines an address range within the received prefix.
// This is used for Mode 1 where you reserve a portion of your /64 that
// the router won't hand out via DHCPv6/SLAAC.
type AddressRangeSpecApplyConfiguration struct {
	// Name identifies this address range (used in annotations to reference it)
	Name *string `json:"name,omitempty"`
	// Start is the start of the range, specified as a suffix to the prefix.
	// For example, "::f000:0:0:0" means start at prefix + 0xf000:0:0:0.
	Start *string `json:"start,omitempty"`
	// End is the end of the range (inclusive), specified as a suffix.
	// For example, "::ffff:ffff:ffff:ffff" means end at prefix + 0xffff:ffff:ffff:ffff.
	End *string `json:"end,omitempty"`
}

// AddressRangeSpecApplyConfiguration constructs a declarative configuration of the AddressRangeSpec type for use with
// apply.
func AddressRangeSpec() *AddressRangeSpecApplyConfiguration {
	return &AddressRangeSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AddressRangeSpecApplyConfiguration) WithName(value string) *AddressRangeSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *AddressRangeSpecApplyConfiguration) WithStart(value string) *AddressRangeSpecApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *AddressRangeSpecApplyConfiguration) WithEnd(value string) *AddressRangeSpecApplyConfiguration {
	b.End = &value
	return b
}
