// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AddressRangeStatusApplyConfiguration represents a declarative configuration of the AddressRangeStatus type for use
// with apply.
//
// AddressRangeStatus represents the current state of an address range
type AddressRangeStatusApplyConfiguration struct {
	// Name is the address range identifier
	Name *string `json:"name,omitempty"`
	// Start is the first address in the range (full address)
	Start *string `json:"start,omitempty"`
	// End is the last address in the range (full address)
	End *string `json:"end,omitempty"`
	// CIDR is an approximate CIDR representation for compatibility.
	// For Cilium pools, use Start/End for precise range definition.
	// This may be a larger range if the start/end don't align to CIDR boundaries.
	CIDR *string `json:"cidr,omitempty"`
}

// AddressRangeStatusApplyConfiguration constructs a declarative configuration of the AddressRangeStatus type for use with
// apply.
func AddressRangeStatus() *AddressRangeStatusApplyConfiguration {
	return &AddressRangeStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AddressRangeStatusApplyConfiguration) WithName(value string) *AddressRangeStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *AddressRangeStatusApplyConfiguration) WithStart(value string) *AddressRangeStatusApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *AddressRangeStatusApplyConfiguration) WithEnd(value string) *AddressRangeStatusApplyConfiguration {
	b.End = &value
	return b
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *AddressRangeStatusApplyConfiguration) WithCIDR(value string) *AddressRangeStatusApplyConfiguration {
	b.CIDR = &value
	return b
}
