// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DHCPv6PDSpecApplyConfiguration represents a declarative configuration of the DHCPv6PDSpec type for use
// with apply.
//
// DHCPv6PDSpec configures the DHCPv6 Prefix Delegation client
type DHCPv6PDSpecApplyConfiguration struct {
	// Interface is the network interface to receive the delegated prefix on
	Interface *string `json:"interface,omitempty"`
	// RequestedPrefixLength hints the desired prefix length to request
	RequestedPrefixLength *int `json:"requestedPrefixLength,omitempty"`
}

// DHCPv6PDSpecApplyConfiguration constructs a declarative configuration of the DHCPv6PDSpec type for use with
// apply.
func DHCPv6PDSpec() *DHCPv6PDSpecApplyConfiguration {
	return &DHCPv6PDSpecApplyConfiguration{}
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *DHCPv6PDSpecApplyConfiguration) WithInterface(value string) *DHCPv6PDSpecApplyConfiguration {
	b.Interface = &value
	return b
}

// WithRequestedPrefixLength sets the RequestedPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestedPrefixLength field is set to the value of the last call.
func (b *DHCPv6PDSpecApplyConfiguration) WithRequestedPrefixLength(value int) *DHCPv6PDSpecApplyConfiguration {
	b.RequestedPrefixLength = &value
	return b
}
