// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1"
	internal "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DynamicPrefixApplyConfiguration represents a declarative configuration of the DynamicPrefix type for use
// with apply.
//
// DynamicPrefix is the Schema for the dynamicprefixes API.
// It represents a dynamically acquired IPv6 prefix that can be subdivided
// into subnets and used to populate supported pool backends and other resources.
type DynamicPrefixApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// Spec defines the desired state of DynamicPrefix
	Spec *DynamicPrefixSpecApplyConfiguration `json:"spec,omitempty"`
	// Status defines the observed state of DynamicPrefix
	Status *DynamicPrefixStatusApplyConfiguration `json:"status,omitempty"`
}

// DynamicPrefix constructs a declarative configuration of the DynamicPrefix type for use with
// apply.
func DynamicPrefix(name string) *DynamicPrefixApplyConfiguration {
	b := &DynamicPrefixApplyConfiguration{}
	b.WithName(name)
	b.WithKind("DynamicPrefix")
	b.WithAPIVersion("dynamic-prefix.io/v1alpha1")
	return b
}

// ExtractDynamicPrefixFrom extracts the applied configuration owned by fieldManager from
// dynamicPrefix for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// dynamicPrefix must be a unmodified DynamicPrefix API object that was retrieved from the Kubernetes API.
// ExtractDynamicPrefixFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDynamicPrefixFrom(dynamicPrefix *apiv1alpha1.DynamicPrefix, fieldManager string, subresource string) (*DynamicPrefixApplyConfiguration, error) {
	b := &DynamicPrefixApplyConfiguration{}
	err := managedfields.ExtractInto(dynamicPrefix, internal.Parser().Type("com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefix"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(dynamicPrefix.Name)

	b.WithKind("DynamicPrefix")
	b.WithAPIVersion("dynamic-prefix.io/v1alpha1")
	return b, nil
}

// ExtractDynamicPrefix extracts the applied configuration owned by fieldManager from
// dynamicPrefix. If no managedFields are found in dynamicPrefix for fieldManager, a
// DynamicPrefixApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// dynamicPrefix must be a unmodified DynamicPrefix API object that was retrieved from the Kubernetes API.
// ExtractDynamicPrefix provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDynamicPrefix(dynamicPrefix *apiv1alpha1.DynamicPrefix, fieldManager string) (*DynamicPrefixApplyConfiguration, error) {
	return ExtractDynamicPrefixFrom(dynamicPrefix, fieldManager, "")
}

// ExtractDynamicPrefixStatus extracts the applied configuration owned by fieldManager from
// dynamicPrefix for the status subresource.
func ExtractDynamicPrefixStatus(dynamicPrefix *apiv1alpha1.DynamicPrefix, fieldManager string) (*DynamicPrefixApplyConfiguration, error) {
	return ExtractDynamicPrefixFrom(dynamicPrefix, fieldManager, "status")
}

func (b DynamicPrefixApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithKind(value string) *DynamicPrefixApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithAPIVersion(value string) *DynamicPrefixApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithName(value string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithGenerateName(value string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithNamespace(value string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithUID(value types.UID) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithResourceVersion(value string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithGeneration(value int64) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithCreationTimestamp(value metav1.Time) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *DynamicPrefixApplyConfiguration) WithLabels(entries map[string]string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *DynamicPrefixApplyConfiguration) WithAnnotations(entries map[string]string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *DynamicPrefixApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *DynamicPrefixApplyConfiguration) WithFinalizers(values ...string) *DynamicPrefixApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *DynamicPrefixApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithSpec(value *DynamicPrefixSpecApplyConfiguration) *DynamicPrefixApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DynamicPrefixApplyConfiguration) WithStatus(value *DynamicPrefixStatusApplyConfiguration) *DynamicPrefixApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *DynamicPrefixApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *DynamicPrefixApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *DynamicPrefixApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *DynamicPrefixApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
