// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DynamicPrefixStatusApplyConfiguration represents a declarative configuration of the DynamicPrefixStatus type for use
// with apply.
//
// DynamicPrefixStatus defines the observed state of DynamicPrefix
type DynamicPrefixStatusApplyConfiguration struct {
	// CurrentPrefix is the currently active IPv6 prefix in CIDR notation
	CurrentPrefix *string `json:"currentPrefix,omitempty"`
	// PrefixSource indicates how the prefix was obtained
	PrefixSource *apiv1alpha1.PrefixSource `json:"prefixSource,omitempty"`
	// LeaseExpiresAt indicates when the DHCPv6 lease expires
	LeaseExpiresAt *v1.Time `json:"leaseExpiresAt,omitempty"`
	// AddressRanges contains the calculated address ranges
	AddressRanges []AddressRangeStatusApplyConfiguration `json:"addressRanges,omitempty"`
	// Subnets contains the calculated subnet CIDRs
	Subnets []SubnetStatusApplyConfiguration `json:"subnets,omitempty"`
	// History contains previous prefixes
	History []PrefixHistoryEntryApplyConfiguration `json:"history,omitempty"`
	// Conditions represent the current state of the DynamicPrefix
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DynamicPrefixStatusApplyConfiguration constructs a declarative configuration of the DynamicPrefixStatus type for use with
// apply.
func DynamicPrefixStatus() *DynamicPrefixStatusApplyConfiguration {
	return &DynamicPrefixStatusApplyConfiguration{}
}

// WithCurrentPrefix sets the CurrentPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentPrefix field is set to the value of the last call.
func (b *DynamicPrefixStatusApplyConfiguration) WithCurrentPrefix(value string) *DynamicPrefixStatusApplyConfiguration {
	b.CurrentPrefix = &value
	return b
}

// WithPrefixSource sets the PrefixSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixSource field is set to the value of the last call.
func (b *DynamicPrefixStatusApplyConfiguration) WithPrefixSource(value apiv1alpha1.PrefixSource) *DynamicPrefixStatusApplyConfiguration {
	b.PrefixSource = &value
	return b
}

// WithLeaseExpiresAt sets the LeaseExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseExpiresAt field is set to the value of the last call.
func (b *DynamicPrefixStatusApplyConfiguration) WithLeaseExpiresAt(value v1.Time) *DynamicPrefixStatusApplyConfiguration {
	b.LeaseExpiresAt = &value
	return b
}

// WithAddressRanges adds the given value to the AddressRanges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AddressRanges field.
func (b *DynamicPrefixStatusApplyConfiguration) WithAddressRanges(values ...*AddressRangeStatusApplyConfiguration) *DynamicPrefixStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAddressRanges")
		}
		b.AddressRanges = append(b.AddressRanges, *values[i])
	}
	return b
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *DynamicPrefixStatusApplyConfiguration) WithSubnets(values ...*SubnetStatusApplyConfiguration) *DynamicPrefixStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubnets")
		}
		b.Subnets = append(b.Subnets, *values[i])
	}
	return b
}

// WithHistory adds the given value to the History field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the History field.
func (b *DynamicPrefixStatusApplyConfiguration) WithHistory(values ...*PrefixHistoryEntryApplyConfiguration) *DynamicPrefixStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHistory")
		}
		b.History = append(b.History, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DynamicPrefixStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DynamicPrefixStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
