// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DynamicPrefixSpecApplyConfiguration represents a declarative configuration of the DynamicPrefixSpec type for use
// with apply.
//
// DynamicPrefixSpec defines the desired state of DynamicPrefix
type DynamicPrefixSpecApplyConfiguration struct {
	// Acquisition defines how to receive the IPv6 prefix
	Acquisition *AcquisitionSpecApplyConfiguration `json:"acquisition,omitempty"`
	// AddressRanges defines address ranges within the received prefix.
	// Use this for Mode 1 (recommended): reserve a range within your /64 that
	// your router's DHCPv6/SLAAC won't hand out. No BGP required.
	AddressRanges []AddressRangeSpecApplyConfiguration `json:"addressRanges,omitempty"`
	// Subnets defines how to subdivide the received prefix into smaller subnets.
	// Use this for Mode 2 (advanced): carve out dedicated /64s from a larger
	// prefix. Requires BGP to announce the subnets to your router.
	Subnets []SubnetSpecApplyConfiguration `json:"subnets,omitempty"`
	// Transition defines graceful transition settings when prefix changes
	Transition *TransitionSpecApplyConfiguration `json:"transition,omitempty"`
}

// DynamicPrefixSpecApplyConfiguration constructs a declarative configuration of the DynamicPrefixSpec type for use with
// apply.
func DynamicPrefixSpec() *DynamicPrefixSpecApplyConfiguration {
	return &DynamicPrefixSpecApplyConfiguration{}
}

// WithAcquisition sets the Acquisition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Acquisition field is set to the value of the last call.
func (b *DynamicPrefixSpecApplyConfiguration) WithAcquisition(value *AcquisitionSpecApplyConfiguration) *DynamicPrefixSpecApplyConfiguration {
	b.Acquisition = value
	return b
}

// WithAddressRanges adds the given value to the AddressRanges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AddressRanges field.
func (b *DynamicPrefixSpecApplyConfiguration) WithAddressRanges(values ...*AddressRangeSpecApplyConfiguration) *DynamicPrefixSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAddressRanges")
		}
		b.AddressRanges = append(b.AddressRanges, *values[i])
	}
	return b
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *DynamicPrefixSpecApplyConfiguration) WithSubnets(values ...*SubnetSpecApplyConfiguration) *DynamicPrefixSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubnets")
		}
		b.Subnets = append(b.Subnets, *values[i])
	}
	return b
}

// WithTransition sets the Transition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transition field is set to the value of the last call.
func (b *DynamicPrefixSpecApplyConfiguration) WithTransition(value *TransitionSpecApplyConfiguration) *DynamicPrefixSpecApplyConfiguration {
	b.Transition = value
	return b
}
