// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PrefixHistoryEntryApplyConfiguration represents a declarative configuration of the PrefixHistoryEntry type for use
// with apply.
//
// PrefixHistoryEntry represents a historical prefix
type PrefixHistoryEntryApplyConfiguration struct {
	// Prefix is the historical prefix in CIDR notation
	Prefix *string `json:"prefix,omitempty"`
	// AcquiredAt is when this prefix was first acquired
	AcquiredAt *v1.Time `json:"acquiredAt,omitempty"`
	// DeprecatedAt is when this prefix was replaced by a new one
	DeprecatedAt *v1.Time `json:"deprecatedAt,omitempty"`
	// State indicates the current state of this historical prefix
	State *apiv1alpha1.PrefixState `json:"state,omitempty"`
}

// PrefixHistoryEntryApplyConfiguration constructs a declarative configuration of the PrefixHistoryEntry type for use with
// apply.
func PrefixHistoryEntry() *PrefixHistoryEntryApplyConfiguration {
	return &PrefixHistoryEntryApplyConfiguration{}
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *PrefixHistoryEntryApplyConfiguration) WithPrefix(value string) *PrefixHistoryEntryApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithAcquiredAt sets the AcquiredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcquiredAt field is set to the value of the last call.
func (b *PrefixHistoryEntryApplyConfiguration) WithAcquiredAt(value v1.Time) *PrefixHistoryEntryApplyConfiguration {
	b.AcquiredAt = &value
	return b
}

// WithDeprecatedAt sets the DeprecatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeprecatedAt field is set to the value of the last call.
func (b *PrefixHistoryEntryApplyConfiguration) WithDeprecatedAt(value v1.Time) *PrefixHistoryEntryApplyConfiguration {
	b.DeprecatedAt = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PrefixHistoryEntryApplyConfiguration) WithState(value apiv1alpha1.PrefixState) *PrefixHistoryEntryApplyConfiguration {
	b.State = &value
	return b
}
