// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PrefixFilterSpecApplyConfiguration represents a declarative configuration of the PrefixFilterSpec type for use
// with apply.
//
// PrefixFilterSpec constrains which acquired prefixes the operator will accept.
type PrefixFilterSpecApplyConfiguration struct {
	// RequireGlobalUnicast rejects any acquired prefix outside 2000::/3, notably
	// unique-local (fc00::/7) and link-local (fe80::/10).
	//
	// A delegated prefix is global unicast by definition, so this defaults to true.
	// It matters because a link can advertise several prefixes: if a Router
	// Advertisement carries no global prefix -- during upstream renegotiation, or on
	// a link where a unique-local prefix is advertised alongside -- a receiver that
	// merely prefers global unicast will accept the unique-local one and rotate it
	// in as though the delegation had changed. Every address the operator derives
	// then moves into a range that is not routable off-link, and the displaced
	// prefix ages out of history as if it were genuinely retired.
	//
	// Set to false only when the prefix being tracked is deliberately not global
	// unicast, which is unusual outside test environments.
	RequireGlobalUnicast *bool `json:"requireGlobalUnicast,omitempty"`
	// MinPrefixLength rejects any acquired prefix shorter than this, counted in
	// bits, so a larger number is a smaller prefix.
	//
	// An upstream that hands back something far larger than expected -- or an
	// advertisement from a router that should not be delegating at all -- is
	// otherwise taken at face value, and every derived range moves with it.
	// Bounding the length is the cheapest way to say what a plausible
	// delegation looks like on this link. Applies to every acquisition source.
	MinPrefixLength *int `json:"minPrefixLength,omitempty"`
	// MaxPrefixLength rejects any acquired prefix longer than this, counted in
	// bits. Applies to every acquisition source.
	MaxPrefixLength *int `json:"maxPrefixLength,omitempty"`
}

// PrefixFilterSpecApplyConfiguration constructs a declarative configuration of the PrefixFilterSpec type for use with
// apply.
func PrefixFilterSpec() *PrefixFilterSpecApplyConfiguration {
	return &PrefixFilterSpecApplyConfiguration{}
}

// WithRequireGlobalUnicast sets the RequireGlobalUnicast field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireGlobalUnicast field is set to the value of the last call.
func (b *PrefixFilterSpecApplyConfiguration) WithRequireGlobalUnicast(value bool) *PrefixFilterSpecApplyConfiguration {
	b.RequireGlobalUnicast = &value
	return b
}

// WithMinPrefixLength sets the MinPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinPrefixLength field is set to the value of the last call.
func (b *PrefixFilterSpecApplyConfiguration) WithMinPrefixLength(value int) *PrefixFilterSpecApplyConfiguration {
	b.MinPrefixLength = &value
	return b
}

// WithMaxPrefixLength sets the MaxPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPrefixLength field is set to the value of the last call.
func (b *PrefixFilterSpecApplyConfiguration) WithMaxPrefixLength(value int) *PrefixFilterSpecApplyConfiguration {
	b.MaxPrefixLength = &value
	return b
}
