// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RouterAdvertisementSpecApplyConfiguration represents a declarative configuration of the RouterAdvertisementSpec type for use
// with apply.
//
// RouterAdvertisementSpec configures Router Advertisement monitoring
type RouterAdvertisementSpecApplyConfiguration struct {
	// Interface is the network interface to monitor for Router Advertisements
	Interface *string `json:"interface,omitempty"`
	// Enabled controls whether RA monitoring is active. Defaults to true.
	//
	// A pointer, because the pair "omitempty" and "default=true" cannot express
	// false on a plain bool: the zero value is indistinguishable from unset, so a
	// Go client round-tripping this object drops `enabled: false` from the JSON
	// and the API server defaults it straight back to true. PrefixFilterSpec
	// already models an opt-out this way.
	Enabled *bool `json:"enabled,omitempty"`
	// TrustedRouters restricts accepted Router Advertisements to those sent
	// from these link-local addresses -- the fe80:: address the router uses on
	// this link, which is what an advertisement's source address carries.
	//
	// Anything on the link can send a Router Advertisement, and the RFC 4861
	// checks the receiver already applies say only that the sender is on-link
	// and one hop away, which is true of every host on the segment. Naming the
	// routers that may be believed is what turns that into a trust decision.
	// Advertisements from anywhere else are dropped, counted and reported.
	//
	// Leave empty on a link you control, where switch-side RA Guard does this
	// job, or where DHCPv6-PD is used instead.
	TrustedRouters []string `json:"trustedRouters,omitempty"`
}

// RouterAdvertisementSpecApplyConfiguration constructs a declarative configuration of the RouterAdvertisementSpec type for use with
// apply.
func RouterAdvertisementSpec() *RouterAdvertisementSpecApplyConfiguration {
	return &RouterAdvertisementSpecApplyConfiguration{}
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *RouterAdvertisementSpecApplyConfiguration) WithInterface(value string) *RouterAdvertisementSpecApplyConfiguration {
	b.Interface = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *RouterAdvertisementSpecApplyConfiguration) WithEnabled(value bool) *RouterAdvertisementSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithTrustedRouters adds the given value to the TrustedRouters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TrustedRouters field.
func (b *RouterAdvertisementSpecApplyConfiguration) WithTrustedRouters(values ...string) *RouterAdvertisementSpecApplyConfiguration {
	for i := range values {
		b.TrustedRouters = append(b.TrustedRouters, values[i])
	}
	return b
}
