// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SubnetStatusApplyConfiguration represents a declarative configuration of the SubnetStatus type for use
// with apply.
//
// SubnetStatus represents the current state of a subnet
type SubnetStatusApplyConfiguration struct {
	// Name is the subnet identifier
	Name *string `json:"name,omitempty"`
	// CIDR is the calculated subnet in CIDR notation
	CIDR *string `json:"cidr,omitempty"`
	// BGPAdvertisement is the name of the managed CiliumBGPAdvertisement resource.
	// Only set when bgp.advertise is true for this subnet.
	BGPAdvertisement *string `json:"bgpAdvertisement,omitempty"`
}

// SubnetStatusApplyConfiguration constructs a declarative configuration of the SubnetStatus type for use with
// apply.
func SubnetStatus() *SubnetStatusApplyConfiguration {
	return &SubnetStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubnetStatusApplyConfiguration) WithName(value string) *SubnetStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *SubnetStatusApplyConfiguration) WithCIDR(value string) *SubnetStatusApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithBGPAdvertisement sets the BGPAdvertisement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGPAdvertisement field is set to the value of the last call.
func (b *SubnetStatusApplyConfiguration) WithBGPAdvertisement(value string) *SubnetStatusApplyConfiguration {
	b.BGPAdvertisement = &value
	return b
}
