// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SubnetSpecApplyConfiguration represents a declarative configuration of the SubnetSpec type for use
// with apply.
//
// SubnetSpec defines a subnet to be carved out of the received prefix.
// This is used for Mode 2 (advanced) where you claim a dedicated /64 from
// a larger prefix and announce it via BGP.
type SubnetSpecApplyConfiguration struct {
	// Name identifies this subnet (used in annotations to reference it)
	Name *string `json:"name,omitempty"`
	// Offset selects the Nth subnet of PrefixLength within the received prefix.
	// For example, with a /56 base prefix and PrefixLength 64, offset 255 selects
	// the last /64 in the /56.
	Offset *int64 `json:"offset,omitempty"`
	// PrefixLength is the prefix length of the subnet (e.g., 120 for a /120)
	PrefixLength *int `json:"prefixLength,omitempty"`
	// BGP configures BGP advertisement for LoadBalancer IPs from this subnet.
	// Requires Cilium BGP Control Plane to be enabled and peering configured separately.
	BGP *SubnetBGPSpecApplyConfiguration `json:"bgp,omitempty"`
}

// SubnetSpecApplyConfiguration constructs a declarative configuration of the SubnetSpec type for use with
// apply.
func SubnetSpec() *SubnetSpecApplyConfiguration {
	return &SubnetSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithName(value string) *SubnetSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithOffset sets the Offset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Offset field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithOffset(value int64) *SubnetSpecApplyConfiguration {
	b.Offset = &value
	return b
}

// WithPrefixLength sets the PrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixLength field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithPrefixLength(value int) *SubnetSpecApplyConfiguration {
	b.PrefixLength = &value
	return b
}

// WithBGP sets the BGP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGP field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithBGP(value *SubnetBGPSpecApplyConfiguration) *SubnetSpecApplyConfiguration {
	b.BGP = value
	return b
}
