// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SubnetBGPSpecApplyConfiguration represents a declarative configuration of the SubnetBGPSpec type for use
// with apply.
//
// SubnetBGPSpec configures BGP advertisement for a subnet.
type SubnetBGPSpecApplyConfiguration struct {
	// Advertise enables BGP advertisement of LoadBalancer IPs from this subnet.
	// When true, the operator creates a CiliumBGPAdvertisement resource that
	// causes Cilium to announce individual Service IPs (/128) to BGP peers.
	Advertise *bool `json:"advertise,omitempty"`
	// Community is the BGP community to attach to advertisements.
	// Format: "ASN:VALUE" (e.g., "65001:100").
	// The router should be configured to filter and only accept routes with this community.
	// This provides an additional layer of security beyond prefix-length filtering.
	Community *string `json:"community,omitempty"`
}

// SubnetBGPSpecApplyConfiguration constructs a declarative configuration of the SubnetBGPSpec type for use with
// apply.
func SubnetBGPSpec() *SubnetBGPSpecApplyConfiguration {
	return &SubnetBGPSpecApplyConfiguration{}
}

// WithAdvertise sets the Advertise field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Advertise field is set to the value of the last call.
func (b *SubnetBGPSpecApplyConfiguration) WithAdvertise(value bool) *SubnetBGPSpecApplyConfiguration {
	b.Advertise = &value
	return b
}

// WithCommunity sets the Community field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Community field is set to the value of the last call.
func (b *SubnetBGPSpecApplyConfiguration) WithCommunity(value string) *SubnetBGPSpecApplyConfiguration {
	b.Community = &value
	return b
}
