// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1"
)

// TransitionSpecApplyConfiguration represents a declarative configuration of the TransitionSpec type for use
// with apply.
//
// TransitionSpec defines settings for graceful prefix transitions
type TransitionSpecApplyConfiguration struct {
	// Mode specifies the transition behavior.
	// "simple" (default): Keep multiple blocks in pool, Services keep old IPs until block removed.
	// "ha": Keep both old and new IPs on Service, DNS points to new IP only via external-dns annotation.
	Mode *apiv1alpha1.TransitionMode `json:"mode,omitempty"`
	// MaxPrefixHistory is the maximum number of previous prefixes to retain in pool blocks.
	// When a new prefix is received, historical prefixes beyond this limit are dropped.
	MaxPrefixHistory *int `json:"maxPrefixHistory,omitempty"`
}

// TransitionSpecApplyConfiguration constructs a declarative configuration of the TransitionSpec type for use with
// apply.
func TransitionSpec() *TransitionSpecApplyConfiguration {
	return &TransitionSpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TransitionSpecApplyConfiguration) WithMode(value apiv1alpha1.TransitionMode) *TransitionSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithMaxPrefixHistory sets the MaxPrefixHistory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPrefixHistory field is set to the value of the last call.
func (b *TransitionSpecApplyConfiguration) WithMaxPrefixHistory(value int) *TransitionSpecApplyConfiguration {
	b.MaxPrefixHistory = &value
	return b
}
