// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1"
	apiv1alpha1 "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/pkizzle/dynamic-prefix-operator/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=dynamic-prefix.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AcquisitionSpec"):
		return &apiv1alpha1.AcquisitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AddressRangeSpec"):
		return &apiv1alpha1.AddressRangeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AddressRangeStatus"):
		return &apiv1alpha1.AddressRangeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DHCPv6PDSpec"):
		return &apiv1alpha1.DHCPv6PDSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DynamicPrefix"):
		return &apiv1alpha1.DynamicPrefixApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DynamicPrefixSpec"):
		return &apiv1alpha1.DynamicPrefixSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DynamicPrefixStatus"):
		return &apiv1alpha1.DynamicPrefixStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PrefixFilterSpec"):
		return &apiv1alpha1.PrefixFilterSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PrefixHistoryEntry"):
		return &apiv1alpha1.PrefixHistoryEntryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RouterAdvertisementSpec"):
		return &apiv1alpha1.RouterAdvertisementSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubnetBGPSpec"):
		return &apiv1alpha1.SubnetBGPSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubnetSpec"):
		return &apiv1alpha1.SubnetSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubnetStatus"):
		return &apiv1alpha1.SubnetStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TransitionSpec"):
		return &apiv1alpha1.TransitionSpecApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
