// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AcquisitionSpec
  map:
    fields:
    - name: dhcpv6pd
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DHCPv6PDSpec
    - name: prefixFilter
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixFilterSpec
    - name: routerAdvertisement
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.RouterAdvertisementSpec
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AddressRangeSpec
  map:
    fields:
    - name: end
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: start
      type:
        scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AddressRangeStatus
  map:
    fields:
    - name: cidr
      type:
        scalar: string
    - name: end
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: start
      type:
        scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DHCPv6PDSpec
  map:
    fields:
    - name: interface
      type:
        scalar: string
    - name: requestedPrefixLength
      type:
        scalar: numeric
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefix
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefixSpec
    - name: status
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefixStatus
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefixSpec
  map:
    fields:
    - name: acquisition
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AcquisitionSpec
    - name: addressRanges
      type:
        list:
          elementType:
            namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AddressRangeSpec
          elementRelationship: associative
          keys:
          - name
    - name: subnets
      type:
        list:
          elementType:
            namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetSpec
          elementRelationship: associative
          keys:
          - name
    - name: transition
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.TransitionSpec
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.DynamicPrefixStatus
  map:
    fields:
    - name: addressRanges
      type:
        list:
          elementType:
            namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.AddressRangeStatus
          elementRelationship: atomic
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: currentPrefix
      type:
        scalar: string
    - name: history
      type:
        list:
          elementType:
            namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixHistoryEntry
          elementRelationship: atomic
    - name: leaseExpiresAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: prefixSource
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixSource
    - name: subnets
      type:
        list:
          elementType:
            namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetStatus
          elementRelationship: atomic
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixFilterSpec
  map:
    fields:
    - name: maxPrefixLength
      type:
        scalar: numeric
    - name: minPrefixLength
      type:
        scalar: numeric
    - name: requireGlobalUnicast
      type:
        scalar: boolean
      default: true
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixHistoryEntry
  map:
    fields:
    - name: acquiredAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deprecatedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: prefix
      type:
        scalar: string
    - name: state
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixState
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixSource
  scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.PrefixState
  scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.RouterAdvertisementSpec
  map:
    fields:
    - name: enabled
      type:
        scalar: boolean
      default: true
    - name: interface
      type:
        scalar: string
    - name: trustedRouters
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetBGPSpec
  map:
    fields:
    - name: advertise
      type:
        scalar: boolean
    - name: community
      type:
        scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetSpec
  map:
    fields:
    - name: bgp
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetBGPSpec
    - name: name
      type:
        scalar: string
    - name: offset
      type:
        scalar: numeric
      default: 0
    - name: prefixLength
      type:
        scalar: numeric
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.SubnetStatus
  map:
    fields:
    - name: bgpAdvertisement
      type:
        scalar: string
    - name: cidr
      type:
        scalar: string
    - name: name
      type:
        scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.TransitionMode
  scalar: string
- name: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.TransitionSpec
  map:
    fields:
    - name: maxPrefixHistory
      type:
        scalar: numeric
      default: 2
    - name: mode
      type:
        namedType: com.github.pkizzle.dynamic-prefix-operator.api.v1alpha1.TransitionMode
      default: simple
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
